apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: onboardingdocuments-blob
  title: onboardingdocuments
  description: Onboarding Documents
spec:
  type: blob-container
  lifecycle: production
  owner: team-infra
  system: onboarding
  dependsOn: 
    - resource:azure-blob-storage